// Browsable category labels for Global Feed & Explore. Matching against user profiles is
// done semantically (embedding similarity) in app/api/explore/search/route.ts,
// not by keyword lookup, so no synonym list is needed here.
export const PROFESSIONAL_CATEGORIES: { label: string }[] = [
  { label: 'Software Engineering' },
  { label: 'Product Management' },
  { label: 'Data Science & AI' },
  { label: 'Cybersecurity & Cloud' },
  { label: 'Marketing' },
  { label: 'Sales' },
  { label: 'Design & UX' },
  { label: 'Finance & Accounting' },
  { label: 'Consulting' },
  { label: 'Human Resources & Talent' },
  { label: 'Operations & Logistics' },
  { label: 'Healthcare & Medicine' },
  { label: 'Education & Research' },
  { label: 'Legal & Compliance' },
  { label: 'Real Estate & Property' },
  { label: 'Entrepreneurship & Startups' },
  { label: 'Venture Capital & Investing' },
  { label: 'Media & Communications' },
  { label: 'Architecture & Construction' },
  { label: 'Biotech & Life Sciences' },
  { label: 'Energy & Sustainability' },
  { label: 'Executive Leadership' },
];
